name: AI Provenance Check

on:
  pull_request:
    branches: [main, master, develop]
  push:
    branches: [main, master, develop]

jobs:
  ai-provenance:
    runs-on: ubuntu-latest
    name: AI Code Provenance Validation

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for provenance tracking

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install AI Provenance
        run: |
          pip install ai-provenance

      - name: Initialize AI Provenance
        run: |
          ai-prov init --verbose || echo "Already initialized"

      - name: Validate Repository
        id: validate
        run: |
          # Run validation with review and test requirements
          ai-prov validate --require-review --require-tests || {
            echo "validation_failed=true" >> $GITHUB_OUTPUT
            exit 1
          }

      - name: Generate Metrics
        if: always()
        id: metrics
        run: |
          # Generate AI percentage metrics
          ai-prov query --ai-percent --by-file > metrics.txt

          # Extract overall percentage
          AI_PERCENT=$(grep "AI-Generated Code:" metrics.txt | awk '{print $3}')
          echo "ai_percent=$AI_PERCENT" >> $GITHUB_OUTPUT

          # Save metrics as artifact
          cat metrics.txt >> $GITHUB_STEP_SUMMARY

      - name: Generate Traceability Matrix
        if: always()
        run: |
          ai-prov trace-matrix --format md >> $GITHUB_STEP_SUMMARY

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const metrics = fs.readFileSync('metrics.txt', 'utf8');

            // Get PR files
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            // Count AI lines in PR
            let aiLines = 0;
            let totalLines = 0;

            for (const file of files) {
              if (file.patch) {
                const lines = file.patch.split('\n');
                const additions = lines.filter(l => l.startsWith('+') && !l.startsWith('+++')).length;
                totalLines += additions;

                // Check for AI metadata
                const hasAI = lines.some(l => l.includes('ai:'));
                if (hasAI) {
                  aiLines += additions;
                }
              }
            }

            const aiPercent = totalLines > 0 ? (aiLines / totalLines * 100).toFixed(1) : 0;

            // Create comment
            const body = `## 🤖 AI Code Provenance Report

**This PR:**
- **AI-generated lines:** ${aiLines} / ${totalLines} (${aiPercent}%)

**Repository-wide metrics:**
\`\`\`
${metrics}
\`\`\`

*Generated by [ai-provenance](https://github.com/ai-provenance/ai-provenance)*
`;

            await github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

      - name: Upload Metrics Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ai-provenance-metrics
          path: metrics.txt

      - name: Check for Unreviewed AI Code
        run: |
          UNREVIEWED=$(ai-prov query --unreviewed)
          if echo "$UNREVIEWED" | grep -q "Found"; then
            echo "⚠️ Warning: Unreviewed AI code detected"
            echo "$UNREVIEWED"
            echo "::warning::Unreviewed AI code detected. Please ensure all AI-generated code is reviewed."
          fi
